name: Publish .NET Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [linux-x64, osx-x64, win-x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish -c Release -r ${{ matrix.os }} --self-contained -p:PublishTrimmed=true -o ./publish

    - name: Archive build (Ubuntu)
      if: matrix.os == 'linux-x64'
      run: tar -czvf exifrenamer-ubuntu.tar.gz -C ./publish .

    - name: Archive build (macOS)
      if: matrix.os == 'osx-x64'
      run: tar -czvf exifrenamer-macos.tar.gz -C ./publish .

    - name: Archive build (Windows)
      if: matrix.os == 'win-x64'
      run: Compress-Archive -Path ./publish/* -DestinationPath exifrenamer-windows.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-build
        path: |
          exifrenamer-ubuntu.tar.gz
          exifrenamer-macos.tar.gz
          exifrenamer-windows.zip
